version: "3.7"

services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    expose:
      - "80"
      - "9000"
    volumes:
      - ${VOLUME_PATH}app_data:/var/www/html
  redis:
    image: redis
    container_name: redis
    volumes:
      - ${VOLUME_PATH}app_data/redis:/var/www/html/data
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - "80"
      - "443"
    volumes:
      - ${VOLUME_PATH}document_data:/var/www/onlyoffice/Data
      - ${VOLUME_PATH}document_log:/var/log/onlyoffice
  mariadb:
    image: mariadb:10.3.12
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    volumes:
      - ${VOLUME_PATH}mysql_data:/var/lib/mysql
  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${VOLUME_PATH}app_data:/var/www/html
volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
