version: "3.7"

services:
  nextcloud:
    container_name: nextcloud_app
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    environment:
      - MYSQL_HOST=nextcloud_mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
      - NEWUID=${NEWUID:-1000}
      - NEWGID=${NEWGID:-1000}

    # command changes www-data to have same uid/gid as a host system's user
    #   easier interoperability of mounted data volumes
    # This may break if the image user www-data UID and GID changes
    command:
      - /bin/sh
      - -c
      - |
        echo Updating www-data uid=$NEWUID gid=$NEWGID
        usermod -u $NEWUID www-data
        groupmod -g $NEWGID www-data
        find / -user 33 -exec chown -h $NEWUID {} \;
        find / -group 33 -exec chgrp -h $NEWGID {} \;
        usermod -g $NEWGID www-data
        php-fpm
    expose:
      - "80"
      - "9000"
    volumes:
      - app_data:/var/www/html
    networks:
      - internal
  redis:
    container_name: nextcloud_redis
    image: redis
    volumes:
      - app_data:/var/www/html/data
    networks:
      - internal
  onlyoffice:
    container_name: nextcloud_onlyoffice
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - "80"
      - "443"
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - internal
  mariadb:
    container_name: nextcloud_mysql
    image: mariadb:10.3.12
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal
  nginx:
    container_name: nextcloud_nginx
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 40480:80
      - 40443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
    networks:
      - internal
      - external
volumes:
  document_data:
    name: nextcloud_document_data
  document_log:
    name: nextcloud_document_log
  mysql_data:
    name: nextcloud_mysql_data
  app_data:
    name: nextcloud_app_data

networks:
  internal:
    external: false
    name: nextcloud_internal
  external:
    external: true
    name: nextcloud_external
