version: "3.7"

services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    expose:
      - "80"
      - "9000"
    volumes:
      - app_data:/var/www/html
      - ${VOLUME_PATH}:/var/external/books
      - ${VOLUME_PATH}:/var/external/homes
    networks:
      - internal
  redis:
    image: redis
    container_name: redis
    volumes:
      - app_data/redis:/var/www/html/data
    networks:
      - internal
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - "80"
      - "443"
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - internal
  mariadb:
    image: mariadb:10.3.12
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal
  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 40480:80
      - 40443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
    networks:
      - internal
      - external
volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:

networks:
  internal:
  external:
    external: true
    name: nextcloud-net
