version: "3.7"

services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    expose:
      - "80"
      - "9000"
    volumes:
      - ${VOLUME_PATH}nextcloud:/var/www/html:cached
    command:
      - /bin/sh
      - -c
      - |
        sleep 10
        apk add --no-cache sudo
        sudo -u www-data php occ --no-warnings app:install onlyoffice
        sudo -u www-data php occ --no-warnings config:system:set onlyoffice DocumentServerUrl --value="/ds-vpath/"
        sudo -u www-data php occ --no-warnings config:system:set onlyoffice DocumentServerInternalUrl --value="http://onlyoffice-document-server/"
        sudo -u www-data php occ --no-warnings config:system:set onlyoffice StorageUrl --value="http://nginx-server/"
        sudo -u www-data php occ --no-warnings config:system:set trusted_proxies 0 --value="172.xx.0.x"
        php-fpm
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - "80"
      - "443"
    volumes:
      - ${VOLUME_PATH}onlyoffice_data:/var/www/onlyoffice/Data
      - ${VOLUME_PATH}onlyoffice_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 40480:80
      - 40443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${VOLUME_PATH}nextcloud:/var/www/html:cached
  mariadb:
    image: mariadb:10.3.12
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    # networks:
    #   - internal
volumes:
  nextcloud:
  mariadb:
  onlyoffice_data:
  onlyoffice_log:
